/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSetup: typeof import('./components/AppSetup.vue')['default']
    AsideNav: typeof import('./components/AsideNav.vue')['default']
    ExternalLinkWarning: typeof import('./components/ExternalLinkWarning.vue')['default']
    HideFooter: typeof import('./components/HideFooter.vue')['default']
    NavPage: typeof import('./components/NavPage.vue')['default']
    PageLoading: typeof import('./components/PageLoading.vue')['default']
    ParticleBackground: typeof import('./components/ParticleBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
